# Generated by Django 3.2.8 on 2021-12-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_auto_20211208_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
